#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef DOTDOCUMENT_SWIFT_H
#define DOTDOCUMENT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import DotCamera;
@import DotCore;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DotDocument",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class DOTDDocumentAutoCaptureFrameParameters;

/// Use this protocol to create document validators.
SWIFT_PROTOCOL_NAMED("DocumentAutoCaptureDetectionValidator")
@protocol DOTDDocumentAutoCaptureDetectionValidator
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Validate current frame parameters.
/// \param documentAutoCaptureFrameParameters Current frame parameters.
///
///
/// returns:
/// Returns <code>false</code> to indicate failed validation.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Validate maximum brightness of the detected document.
/// To use this validator also following validators must be applied: <code>DocumentOutOfBoundsValidator</code>.
SWIFT_CLASS_NAMED("BrightnessTooHighValidator")
@interface DOTDBrightnessTooHighValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.9.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultThreshold;)
+ (double)defaultThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current maximal accepted brightness.
@property (nonatomic, readonly) double threshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithThreshold:(double)threshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate brightness of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for bright document.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Validate minimum brightness of the detected document.
/// To use this validator also following validators must be applied: <code>DocumentOutOfBoundsValidator</code>.
SWIFT_CLASS_NAMED("BrightnessTooLowValidator")
@interface DOTDBrightnessTooLowValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.25.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultThreshold;)
+ (double)defaultThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current minimal accepted brightness.
@property (nonatomic, readonly) double threshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithThreshold:(double)threshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate brightness of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for dark document.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end

@class DOTDQualityAttributeThresholds;
enum DOTDValidationMode : NSInteger;
enum DOTDMrzValidation : NSInteger;
enum DOTDPlaceholderType : NSInteger;

/// Configuration options for the document auto capture process.
SWIFT_CLASS_NAMED("Configuration")
@interface DOTDDocumentAutoCaptureConfiguration : NSObject
/// Customize thresholds for the quality attributes of the document auto capture result.
@property (nonatomic, readonly, strong) DOTDQualityAttributeThresholds * _Nonnull qualityAttributeThresholds;
/// Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to <code>1</code>. Default is <code>2</code>.
@property (nonatomic, readonly) NSInteger minValidFramesInRowToStartCandidateSelection;
/// Duration of candidate selection phase. Value must be greater than or equal to <code>0</code>. Default is <code>2000</code>.
@property (nonatomic, readonly) NSInteger candidateSelectionDurationMillis;
/// Specify validation mode. Default is <code>.standard</code>.
@property (nonatomic, readonly) enum DOTDValidationMode validationMode;
/// Specify MRZ validation. Default is <code>.none</code>.
@property (nonatomic, readonly) enum DOTDMrzValidation mrzValidation;
/// Use this flag to show or hide detection rectangle during the document auto capture process. Default is <code>false</code>.
@property (nonatomic, readonly) BOOL isDetectionLayerVisible;
/// Use this flag to turn the torch on or off during the document auto capture process.
/// Torch will be turned on only if <code>cameraFacing</code> property is set to <code>.back</code>. Default is <code>false</code>.
@property (nonatomic, readonly) BOOL isTorchEnabled;
/// Use this flag to capture a video of the document auto capture process.
/// When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.
/// The captured video is included exclusively in the binary content of the result. Default is <code>false</code>.
@property (nonatomic, readonly) BOOL isVideoCaptureEnabled;
/// Specify camera facing. Default is <code>.back</code>.
@property (nonatomic, readonly) enum DOTCameraFacing cameraFacing;
/// Specify camera preview scale type. Default is <code>.fit</code>.
@property (nonatomic, readonly) enum DOTCameraPreviewScaleType cameraPreviewScaleType;
/// Specify the type of placeholder used in document auto-capture UI. Default is <code>.cornersOnly</code>.
@property (nonatomic, readonly) enum DOTDPlaceholderType placeholderType;
/// Specify if camera preview is visible. Default is <code>true</code>.
@property (nonatomic, readonly) BOOL isCameraPreviewVisible;
/// Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is <code>nil</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable sessionToken;
/// Create the document auto capture configuration with default values.
- (nonnull instancetype)init;
/// Create the document auto capture configuration.
- (nullable instancetype)initWithSessionToken:(NSString * _Nullable)sessionToken qualityAttributeThresholds:(DOTDQualityAttributeThresholds * _Nonnull)qualityAttributeThresholds minValidFramesInRowToStartCandidateSelection:(NSInteger)minValidFramesInRowToStartCandidateSelection candidateSelectionDurationMillis:(NSInteger)candidateSelectionDurationMillis validationMode:(enum DOTDValidationMode)validationMode mrzValidation:(enum DOTDMrzValidation)mrzValidation isDetectionLayerVisible:(BOOL)isDetectionLayerVisible isTorchEnabled:(BOOL)isTorchEnabled isVideoCaptureEnabled:(BOOL)isVideoCaptureEnabled cameraFacing:(enum DOTCameraFacing)cameraFacing cameraPreviewScaleType:(enum DOTCameraPreviewScaleType)cameraPreviewScaleType placeholderType:(enum DOTDPlaceholderType)placeholderType isCameraPreviewVisible:(BOOL)isCameraPreviewVisible error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


@interface DOTDDocumentAutoCaptureConfiguration (SWIFT_EXTENSION(DotDocument))
@end

@class DOTWrappedDouble;
@class DOTIntervalDouble;

/// Configure thresholds for the quality attributes of the document auto capture result.
SWIFT_CLASS_NAMED("QualityAttributeThresholds")
@interface DOTDQualityAttributeThresholds : NSObject
/// Minimal valid confidence of the detected document.
/// Value 0.0 represents low confidence.
/// Vaue 1.0 represents high confidence.
@property (nonatomic, readonly, strong) DOTWrappedDouble * _Nullable minConfidence;
/// Minimal valid size of the detected document.
/// Value 0.0 represents small size.
/// Vaue 1.0 represents large size.
@property (nonatomic, readonly, strong) DOTWrappedDouble * _Nullable minSize;
/// Minimal valid sharpness of the detected document.
/// Value 0.0 represents blurry document.
/// Vaue 1.0 represents sharp document.
@property (nonatomic, readonly, strong) DOTWrappedDouble * _Nullable minSharpness;
/// Valid interval of brightness of the detected document.
/// Value 0.0 represents low brightness.
/// Vaue 1.0 represents high brightness.
@property (nonatomic, readonly, strong) DOTIntervalDouble * _Nullable brightnessInterval;
/// Maximal valid hotspots score of the detected document.
/// Value 0.0 represents low hotspots occurrence.
/// Vaue 1.0 represents high hotspots occurrence.
@property (nonatomic, readonly, strong) DOTWrappedDouble * _Nullable maxHotspotsScore;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end


SWIFT_CLASS_NAMED("Builder")
@interface DOTDQualityAttributeThresholdsBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (DOTDQualityAttributeThresholdsBuilder * _Nullable)minConfidence:(DOTWrappedDouble * _Nullable)minConfidence error:(NSError * _Nullable * _Nullable)error;
- (DOTDQualityAttributeThresholdsBuilder * _Nullable)minSize:(DOTWrappedDouble * _Nullable)minSize error:(NSError * _Nullable * _Nullable)error;
- (DOTDQualityAttributeThresholdsBuilder * _Nullable)minSharpness:(DOTWrappedDouble * _Nullable)minSharpness error:(NSError * _Nullable * _Nullable)error;
- (DOTDQualityAttributeThresholdsBuilder * _Nullable)brightnessInterval:(DOTIntervalDouble * _Nullable)brightnessInterval error:(NSError * _Nullable * _Nullable)error;
- (DOTDQualityAttributeThresholdsBuilder * _Nullable)maxHotspotsScore:(DOTWrappedDouble * _Nullable)maxHotspotsScore error:(NSError * _Nullable * _Nullable)error;
- (DOTDQualityAttributeThresholds * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end


/// Presets for the quality attributes thresholds of the document auto capture result.
SWIFT_CLASS_NAMED("QualityAttributeThresholdPresets")
@interface DOTDQualityAttributeThresholdPresets : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Builder for <code>QualityAttributeThresholds</code> recommended for standard use cases, for example OCR.
/// <code>minConfidence</code> value is 0.9.
/// <code>minSize</code> value is 0.43.
/// <code>minSharpness</code> value is 0.65.
/// <code>brightnessInterval</code> value is [0.25, 0.9].
/// <code>maxHotspotsScore</code> value is 0.008.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DOTDQualityAttributeThresholdsBuilder * _Nonnull standard;)
+ (DOTDQualityAttributeThresholdsBuilder * _Nonnull)standard SWIFT_WARN_UNUSED_RESULT;
@end

@class DOTPointDouble;

/// Position of the document card in the image.
SWIFT_CLASS_NAMED("DetectionPosition")
@interface DOTDDetectionPosition : NSObject
/// Top left corner point.
@property (nonatomic, readonly, strong) DOTPointDouble * _Nonnull topLeft;
/// Top right corner point.
@property (nonatomic, readonly, strong) DOTPointDouble * _Nonnull topRight;
/// Bottom right corner point.
@property (nonatomic, readonly, strong) DOTPointDouble * _Nonnull bottomRight;
/// Bottom left corner point.
@property (nonatomic, readonly, strong) DOTPointDouble * _Nonnull bottomLeft;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithTopLeft:(DOTPointDouble * _Nonnull)topLeft topRight:(DOTPointDouble * _Nonnull)topRight bottomRight:(DOTPointDouble * _Nonnull)bottomRight bottomLeft:(DOTPointDouble * _Nonnull)bottomLeft;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

@class DOTRectangleDouble;

@interface DOTDDetectionPosition (SWIFT_EXTENSION(DotDocument))
@property (nonatomic, readonly, copy) NSArray<DOTPointDouble *> * _Nonnull points;
+ (DOTDDetectionPosition * _Nonnull)fromRectangle:(DOTRectangleDouble * _Nonnull)rectangle SWIFT_WARN_UNUSED_RESULT;
- (DOTDDetectionPosition * _Nonnull)rebasedWithParentRectangle:(DOTRectangleDouble * _Nonnull)parentRectangle SWIFT_WARN_UNUSED_RESULT;
- (DOTDDetectionPosition * _Nonnull)mirrored SWIFT_WARN_UNUSED_RESULT;
@end

@class DOTDDocumentAutoCaptureControllerConfiguration;
@class DOTBgraRawImage;
@class DOTDDocumentAutoCaptureControllerProcessingResult;
@class DOTDDocumentAutoCaptureControllerSample;

/// Non-UI component for the document auto capture process.
SWIFT_CLASS_NAMED("DocumentAutoCaptureController")
@interface DOTDDocumentAutoCaptureController : NSObject
/// Current configuration.
@property (nonatomic, readonly, strong) DOTDDocumentAutoCaptureControllerConfiguration * _Nonnull configuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Create new instance of <code>DocumentAutoCaptureController</code>.
- (nonnull instancetype)initWithConfiguration:(DOTDDocumentAutoCaptureControllerConfiguration * _Nonnull)configuration;
/// Process an input image or video frame and update the state.
/// \param bgraRawImage Input image.
///
/// \param timestampMillis Input image timestamp.
///
///
/// throws:
/// Throws an error if you call this method after the document auto capture process has finished.
///
/// returns:
/// The result of processing of the input image.
- (DOTDDocumentAutoCaptureControllerProcessingResult * _Nullable)processWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage timestampMillis:(NSInteger)timestampMillis error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use process(sample:) instead.");
/// Process an input sample and update the state.
/// \param sample Input sample.
///
///
/// throws:
/// Throws an error if you call this method after the document auto capture process has finished.
///
/// returns:
/// The result of processing of the input sample.
- (DOTDDocumentAutoCaptureControllerProcessingResult * _Nullable)processWithSample:(DOTDDocumentAutoCaptureControllerSample * _Nonnull)sample error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

/// Phase of the document auto capture process.
typedef SWIFT_ENUM_NAMED(NSInteger, DOTDDocumentAutoCaptureControllerPhase, "Phase", open) {
/// Pre-candidate selection is running.
  DOTDDocumentAutoCaptureControllerPhasePreCandidateSelection = 0,
/// Candidate selection is running.
  DOTDDocumentAutoCaptureControllerPhaseCandidateSelection = 1,
};


/// The data sample captured at specific time which serves as an input for the document auto capture process.
SWIFT_CLASS_NAMED("Sample")
@interface DOTDDocumentAutoCaptureControllerSample : NSObject
/// Sample image.
@property (nonatomic, readonly, strong) DOTBgraRawImage * _Nonnull bgraRawImage;
/// Sample timestamp.
@property (nonatomic, readonly) NSInteger timestampMillis;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage timestampMillis:(NSInteger)timestampMillis OBJC_DESIGNATED_INITIALIZER;
@end

@class DOTDDocumentAutoCaptureDetection;
@class DOTDDocumentAutoCaptureResult;

/// The result returned from the processing of one image during the document auto capture process.
SWIFT_CLASS_NAMED("ProcessingResult")
@interface DOTDDocumentAutoCaptureControllerProcessingResult : NSObject
/// The result of processing image during the document auto capture process.
@property (nonatomic, readonly, strong) DOTDDocumentAutoCaptureDetection * _Nonnull detection;
/// The final result of the document auto capture process.
@property (nonatomic, readonly, strong) DOTDDocumentAutoCaptureResult * _Nullable result;
/// Current phase of the document auto capture process.
@property (nonatomic, readonly) enum DOTDDocumentAutoCaptureControllerPhase phase;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithDetection:(DOTDDocumentAutoCaptureDetection * _Nonnull)detection result:(DOTDDocumentAutoCaptureResult * _Nullable)result phase:(enum DOTDDocumentAutoCaptureControllerPhase)phase OBJC_DESIGNATED_INITIALIZER;
@end


@interface DOTDDocumentAutoCaptureController (SWIFT_EXTENSION(DotDocument))
@end


/// Configuration of the document auto capture non-UI component.
SWIFT_CLASS_NAMED("Configuration")
@interface DOTDDocumentAutoCaptureControllerConfiguration : NSObject
/// Array of validators which will be used to validate input image.
@property (nonatomic, readonly, copy) NSArray<id <DOTDDocumentAutoCaptureDetectionValidator>> * _Nonnull validators;
/// Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to <code>1</code>. Default is <code>2</code>.
@property (nonatomic, readonly) NSInteger minValidFramesInRowToStartCandidateSelection;
/// Duration of candidate selection phase. Value must be greater than or equal to <code>0</code>. Default is <code>2000</code>.
@property (nonatomic, readonly) NSInteger candidateSelectionDurationMillis;
/// Normalized rectangle which represents the region in the image which will be used for the document detection.
@property (nonatomic, readonly, strong) DOTRectangleDouble * _Nullable detectionNormalizedRectangle;
/// Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is <code>nil</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable sessionToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Create document auto capture controller configuration.
- (nullable instancetype)initWithSessionToken:(NSString * _Nullable)sessionToken validators:(NSArray<id <DOTDDocumentAutoCaptureDetectionValidator>> * _Nonnull)validators minValidFramesInRowToStartCandidateSelection:(NSInteger)minValidFramesInRowToStartCandidateSelection candidateSelectionDurationMillis:(NSInteger)candidateSelectionDurationMillis detectionNormalizedRectangle:(DOTRectangleDouble * _Nullable)detectionNormalizedRectangle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class DOTDDocumentDetectorDocument;
@class DOTTravelDocumentTypeWrapper;
@class DOTMachineReadableZone;

/// The result of processing video frame during the document auto capture process.
SWIFT_CLASS_NAMED("DocumentAutoCaptureDetection")
@interface DOTDDocumentAutoCaptureDetection : NSObject
/// Detection image.
@property (nonatomic, readonly, strong) DOTBgraRawImage * _Nonnull bgraRawImage;
/// Detected document, or <code>nil</code> if the document was not detected in the image.
@property (nonatomic, readonly, strong) DOTDDocumentDetectorDocument * _Nullable document;
/// Resolved travel document type.
@property (nonatomic, readonly, strong) DOTTravelDocumentTypeWrapper * _Nullable travelDocumentType;
/// Result of MRZ reading.
@property (nonatomic, readonly, strong) DOTMachineReadableZone * _Nullable machineReadableZone;
/// Validator identifiers for which the validation has failed.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull validatorIdentifiers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage document:(DOTDDocumentDetectorDocument * _Nullable)document travelDocumentType:(DOTTravelDocumentTypeWrapper * _Nullable)travelDocumentType machineReadableZone:(DOTMachineReadableZone * _Nullable)machineReadableZone validatorIdentifiers:(NSArray<NSString *> * _Nonnull)validatorIdentifiers OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



@class DOTImageSize;
@class DOTDMrzRecognitionResult;

/// Information from the detection process about the detected document.
SWIFT_CLASS_NAMED("DocumentAutoCaptureFrameParameters")
@interface DOTDDocumentAutoCaptureFrameParameters : NSObject
/// Image size of the detection area.
@property (nonatomic, readonly, strong) DOTImageSize * _Nonnull detectionAreaImageSize;
/// Detected document, or <code>nil</code> if the document was not detected in the image.
@property (nonatomic, readonly, strong) DOTDDocumentDetectorDocument * _Nullable document;
/// Resolved travel document type.
@property (nonatomic, readonly, strong) DOTTravelDocumentTypeWrapper * _Nullable travelDocumentType;
/// Result of MRZ recognition.
@property (nonatomic, readonly, strong) DOTDMrzRecognitionResult * _Nullable mrzRecognitionResult;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithDetectionAreaImageSize:(DOTImageSize * _Nonnull)detectionAreaImageSize document:(DOTDDocumentDetectorDocument * _Nullable)document travelDocumentType:(DOTTravelDocumentTypeWrapper * _Nullable)travelDocumentType mrzRecognitionResult:(DOTDMrzRecognitionResult * _Nullable)mrzRecognitionResult OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


@class NSData;

/// The final result of the document auto capture process.
SWIFT_CLASS_NAMED("DocumentAutoCaptureResult")
@interface DOTDDocumentAutoCaptureResult : NSObject
/// Document image.
@property (nonatomic, readonly, strong) DOTBgraRawImage * _Nonnull bgraRawImage;
/// The result of the document detection. Might be <code>nil</code> only if <code>DocumentAutoCaptureViewController/requestCapture()</code> was used to get the result.
@property (nonatomic, readonly, strong) DOTDDocumentDetectorDocument * _Nullable document;
/// Binary content for server-side evaluation.
@property (nonatomic, readonly, copy) NSData * _Nonnull content;
/// Resolved travel document type.
@property (nonatomic, readonly, strong) DOTTravelDocumentTypeWrapper * _Nullable travelDocumentType;
/// Result of MRZ reading.
@property (nonatomic, readonly, strong) DOTMachineReadableZone * _Nullable machineReadableZone;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage document:(DOTDDocumentDetectorDocument * _Nullable)document content:(NSData * _Nonnull)content travelDocumentType:(DOTTravelDocumentTypeWrapper * _Nullable)travelDocumentType machineReadableZone:(DOTMachineReadableZone * _Nullable)machineReadableZone OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@protocol DOTDDocumentAutoCaptureViewControllerDelegate;
@class DOTDDocumentAutoCaptureStyle;
@class NSCoder;
@class NSBundle;

/// UI component for capturing document images using the placeholder.
SWIFT_CLASS_NAMED("DocumentAutoCaptureViewController")
@interface DOTDDocumentAutoCaptureViewController : UIViewController
/// Set this delegate to handle the document auto capture events.
@property (nonatomic, weak) id <DOTDDocumentAutoCaptureViewControllerDelegate> _Nullable delegate;
/// Current configuration.
@property (nonatomic, readonly, strong) DOTDDocumentAutoCaptureConfiguration * _Nonnull configuration;
/// Current style.
@property (nonatomic, readonly, strong) DOTDDocumentAutoCaptureStyle * _Nonnull style;
/// Create new <code>DocumentAutoCaptureViewController</code>.
/// \param configuration Configure the document auto capture process.
///
/// \param style Customize user interface.
///
- (nonnull instancetype)initWithConfiguration:(DOTDDocumentAutoCaptureConfiguration * _Nonnull)configuration style:(DOTDDocumentAutoCaptureStyle * _Nonnull)style;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
/// Start the document auto capture process.
- (void)start;
/// Stop the document auto capture process asynchronously. The <code>onStopped</code> callback is called after the process has stopped.
- (void)stopAsyncOnStopped:(void (^ _Nonnull)(void))onStopped;
/// Request capture of the next detection.
- (void)requestCapture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface DOTDDocumentAutoCaptureViewController (SWIFT_EXTENSION(DotDocument))
@end

@class UIColor;
@class UIFont;

/// Customization options for the document auto capture user interface.
SWIFT_CLASS_NAMED("Style")
@interface DOTDDocumentAutoCaptureStyle : NSObject
/// Background color of top level view.
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
/// Detection layer color.
@property (nonatomic, readonly, strong) UIColor * _Nonnull detectionLayerColor;
/// Instruction label font.
@property (nonatomic, readonly, strong) UIFont * _Nonnull instructionFont;
/// Instruction label text color.
@property (nonatomic, readonly, strong) UIColor * _Nonnull instructionTextColor;
/// Instruction background color.
@property (nonatomic, readonly, strong) UIColor * _Nonnull instructionBackgroundColor;
/// Instruction label text color during candidate selection phase.
@property (nonatomic, readonly, strong) UIColor * _Nonnull instructionCandidateSelectionTextColor;
/// Instruction background color during candidate selection phase.
@property (nonatomic, readonly, strong) UIColor * _Nonnull instructionCandidateSelectionBackgroundColor;
/// Placeholder color.
@property (nonatomic, readonly, strong) UIColor * _Nonnull placeholderColor;
/// Placeholder overlay color, semi-transparent color is recommended.
@property (nonatomic, readonly, strong) UIColor * _Nonnull placeholderOverlayColor;
/// Placeholder color during candidate selection phase.
@property (nonatomic, readonly, strong) UIColor * _Nonnull placeholderCandidateSelectionColor;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithBackgroundColor:(UIColor * _Nonnull)backgroundColor instructionFont:(UIFont * _Nonnull)instructionFont instructionTextColor:(UIColor * _Nonnull)instructionTextColor instructionCandidateSelectionTextColor:(UIColor * _Nonnull)instructionCandidateSelectionTextColor instructionBackgroundColor:(UIColor * _Nonnull)instructionBackgroundColor instructionCandidateSelectionBackgroundColor:(UIColor * _Nonnull)instructionCandidateSelectionBackgroundColor placeholderColor:(UIColor * _Nonnull)placeholderColor placeholderCandidateSelectionColor:(UIColor * _Nonnull)placeholderCandidateSelectionColor detectionLayerColor:(UIColor * _Nonnull)detectionLayerColor placeholderOverlayColor:(UIColor * _Nonnull)placeholderOverlayColor;
@end



@interface DOTDDocumentAutoCaptureViewController (SWIFT_EXTENSION(DotDocument))
@end





@protocol UIViewControllerTransitionCoordinator;

@interface DOTDDocumentAutoCaptureViewController (SWIFT_EXTENSION(DotDocument))
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


/// Implement this delegate to handle the document auto capture events.
SWIFT_PROTOCOL_NAMED("DocumentAutoCaptureViewControllerDelegate")
@protocol DOTDDocumentAutoCaptureViewControllerDelegate
/// Tells the delegate that the document was captured. This callback is called after the component has stopped.
- (void)documentAutoCaptureViewController:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController captured:(DOTDDocumentAutoCaptureResult * _Nonnull)result;
@optional
/// Tells the delegate that the new detection was processed.
- (void)documentAutoCaptureViewController:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController processed:(DOTDDocumentAutoCaptureDetection * _Nonnull)detection;
/// Tells the delegate that you have no permission for camera usage.
- (void)documentAutoCaptureViewControllerNoCameraPermission:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewDidLoad:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewDidLayoutSubviews:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewWillAppear:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewDidAppear:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewWillDisappear:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewDidDisappear:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
- (void)documentAutoCaptureViewControllerViewWillTransition:(DOTDDocumentAutoCaptureViewController * _Nonnull)viewController;
@end


/// Stateless class which can detect document in an image.
SWIFT_CLASS_NAMED("DocumentDetector")
@interface DOTDDocumentDetector : NSObject
/// Detect documents in an image.
/// This method should be called on the background thread.
/// \param bgraRawImage The image on which the detection is performed.
///
/// \param limit Limit the number of documents to detect. Currently, it is supported to detect only one document.
///
///
/// throws:
/// Throws an error if <code>DocumentDetector</code> fails to execute document detection.
///
/// returns:
/// Array of detected documents.
- (NSArray<DOTDDocumentDetectorDocument *> * _Nullable)detectWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage limit:(NSInteger)limit error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DOTDImageParameters;

/// Result of the document detection process.
SWIFT_CLASS_NAMED("Document")
@interface DOTDDocumentDetectorDocument : NSObject
/// Detected corners of the document card.
@property (nonatomic, readonly, strong) DOTDDetectionPosition * _Nonnull detectionPosition;
/// Document detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence.
@property (nonatomic, readonly) double confidence;
/// Detected width to height ratio of the document.
@property (nonatomic, readonly) double widthToHeightRatio;
/// Image parameters calculated from area of the detected document.
@property (nonatomic, readonly, strong) DOTDImageParameters * _Nonnull imageParameters;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithDetectionPosition:(DOTDDetectionPosition * _Nonnull)detectionPosition confidence:(double)confidence widthToHeightRatio:(double)widthToHeightRatio imageParameters:(DOTDImageParameters * _Nonnull)imageParameters OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// Validates position of the detected document relative to the placeholder.
SWIFT_CLASS_NAMED("DocumentDoesNotFitPlaceholderValidator")
@interface DOTDDocumentDoesNotFitPlaceholderValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.035.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultMaxPenaltyThreshold;)
+ (double)defaultMaxPenaltyThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current maximal penalty threshold. Penalty value is low when detected document is well aligned with placeholder and vice versa.
@property (nonatomic, readonly) double maxPenaltyThreshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Placeholder normalized rectangle.
@property (nonatomic, readonly, strong) DOTRectangleDouble * _Nonnull placeholderNormalizedRectangle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize with custom penalty threshold and normalized placeholder rectangle.
/// \param placeholderNormalizedRectangle Normalized placeholder rectangle.
///
/// \param maxPenaltyThreshold Maximal accepted penalty in range [0, 1.0].
///
///
/// throws:
/// Throws an error if <code>maxPenaltyThreshold</code> is outside of the range [0, 1.0].
- (nullable instancetype)initWithPlaceholderNormalizedRectangle:(DOTRectangleDouble * _Nonnull)placeholderNormalizedRectangle maxPenaltyThreshold:(double)maxPenaltyThreshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Validate position of the detected document relative to the placeholder.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> to indicate that the detected document does not fit the placeholder.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Defines a confidence threshold for document detection.
SWIFT_CLASS_NAMED("DocumentNotDetectedValidator")
@interface DOTDDocumentNotDetectedValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.9.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultMinConfidenceThreshold;)
+ (double)defaultMinConfidenceThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current minimal accepted confidence.
@property (nonatomic, readonly) double minConfidenceThreshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithMinConfidenceThreshold:(double)minConfidenceThreshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate confidence of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> to indicate there was no suitable document detected in the image.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Validate if the detected document is within the bounds of the image.
SWIFT_CLASS_NAMED("DocumentOutOfBoundsValidator")
@interface DOTDDocumentOutOfBoundsValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.03.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultMinCornerDistanceToImageShorterSideRatioThreshold;)
+ (double)defaultMinCornerDistanceToImageShorterSideRatioThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current minimal distance between detected document corner and image edge to image shorter side ratio threshold.
@property (nonatomic, readonly) double minCornerDistanceToImageShorterSideRatioThreshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithMinCornerDistanceToImageShorterSideRatioThreshold:(double)minCornerDistanceToImageShorterSideRatioThreshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate if the detected document is within the bounds of the image.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for out of bounds document.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end

@protocol DotSdkLicenseProxyProtocol;

/// Class responsible for the <code>DotDocument</code> library initialization.
SWIFT_CLASS("_TtC11DotDocument18DotDocumentLibrary")
@interface DotDocumentLibrary : NSObject <DotLibrary>
/// The library identifier.
@property (nonatomic, readonly) enum DotLibraryId id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Initialize library with license.
/// \param license <code>DotSdk</code> license.
///
///
/// throws:
/// Throws an error if the <code>DotDocument</code> library is not enabled in the license.
- (BOOL)initializeWithLicense:(id <DotSdkLicenseProxyProtocol> _Nonnull)license error:(NSError * _Nullable * _Nullable)error;
/// Deinitialize library.
///
/// throws:
/// Throws an error if the <code>DotDocument</code> library fails to deinitialize.
- (BOOL)deinitializeAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


/// Validate hotspots score of the detected document.
/// To use this validator also following validators must be applied: <code>DocumentOutOfBoundsValidator</code>.
SWIFT_CLASS_NAMED("HotspotsScoreTooHighValidator")
@interface DOTDHotspotsScoreTooHighValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.008.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultThreshold;)
+ (double)defaultThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current maximal accepted hotspots score.
@property (nonatomic, readonly) double threshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithThreshold:(double)threshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate hotspots score of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for document with high hotspots occurrence.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Result of image parameters analysis.
SWIFT_CLASS_NAMED("ImageParameters")
@interface DOTDImageParameters : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize <code>ImageParameters</code> with normalized values in range [0, 1.0].
- (nonnull instancetype)initWithSharpness:(double)sharpness brightness:(double)brightness hotspotsScore:(double)hotspotsScore OBJC_DESIGNATED_INITIALIZER;
/// Overall brightness of the document in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness.
@property (nonatomic, readonly) double brightness;
/// Overall sharpness of the document in range [0, 1.0]. Where 0 means low sharpness and 1.0 means high sharpness.
@property (nonatomic, readonly) double sharpness;
/// Overall hotspots score of the document in range [0, 1.0]. Where 0 means low hotspots occurrence and 1.0 means high hotspots occurrence.
@property (nonatomic, readonly) double hotspotsScore;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end



/// Stateless class which can analyze image parameters.
SWIFT_CLASS_NAMED("ImageParametersAnalyzer")
@interface DOTDImageParametersAnalyzer : NSObject
/// Analyze an image and return <code>ImageParameters</code>.
/// \param bgraRawImage Image to analyze.
///
///
/// throws:
/// Throws an error if <code>ImageParametersAnalyzer</code> fails to analyze the image.
///
/// returns:
/// Image parameters which contain: <code>sharpness</code>, <code>brightness</code>, <code>hotspotsScore</code>.
- (DOTDImageParameters * _Nullable)analyzeWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Stateless class which can warp the image perspective and create new image as a result.
SWIFT_CLASS_NAMED("ImagePerspectiveWarper")
@interface DOTDImagePerspectiveWarper : NSObject
/// Warp the image perspective using the document detection result.
/// \param bgraRawImage Input image.
///
/// \param detectionPosition Detected document corners.
///
/// \param targetImageSize Size of the resulting image.
///
///
/// throws:
/// Throws an error if <code>ImagePerspectiveWarper</code> fails to warp the image.
///
/// returns:
/// New warped image.
- (DOTBgraRawImage * _Nullable)warpWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage detectionPosition:(DOTDDetectionPosition * _Nonnull)detectionPosition targetImageSize:(DOTImageSize * _Nonnull)targetImageSize error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Class responsible for the localization of user interface strings.
SWIFT_CLASS_NAMED("Localization")
@interface DOTDLocalization : NSObject
/// You can override default iOS localization mechanism by providing custom translation dictionary.
/// note:
/// You also need to set <code>useLocalizationDictionary</code> flag to <code>true</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nullable localizationDictionary;)
+ (NSDictionary<NSString *, NSString *> * _Nullable)localizationDictionary SWIFT_WARN_UNUSED_RESULT;
+ (void)setLocalizationDictionary:(NSDictionary<NSString *, NSString *> * _Nullable)value;
/// If you set this to <code>true</code>, <code>localizationDictionary</code> will be used to localize strings. Default value is <code>false</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL useLocalizationDictionary;)
+ (BOOL)useLocalizationDictionary SWIFT_WARN_UNUSED_RESULT;
+ (void)setUseLocalizationDictionary:(BOOL)value;
/// Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically <code>Bundle.main</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (void)setBundle:(NSBundle * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Static class responsible for generating logs. You can configure log level.
SWIFT_CLASS_NAMED("Logger")
@interface DOTDLogger : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Log level currently in use. Default value is <code>.none</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum DOTLoggerLogLevel logLevel;)
+ (enum DOTLoggerLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum DOTLoggerLogLevel)newValue;
+ (void)debug:(NSString * _Nullable)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function;
+ (void)info:(NSString * _Nullable)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function;
+ (void)warning:(NSString * _Nullable)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function;
+ (void)error:(NSString * _Nullable)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function;
@end


/// Validate if Machine Readable Zone is present.
SWIFT_CLASS_NAMED("MrzNotPresentValidator")
@interface DOTDMrzNotPresentValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
- (nonnull instancetype)init;
/// Validate presence of MRZ on the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for document with missing MRZ.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Validate Machine Readable Zone.
SWIFT_CLASS_NAMED("MrzNotValidValidator")
@interface DOTDMrzNotValidValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
- (nonnull instancetype)init;
/// Validate MRZ on the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for document with invalid MRZ. If MRZ is not present returns <code>true</code>.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end

@class DOTDMrzReaderResult;

/// Stateless class which can read MRZ using image and document detection result.
SWIFT_CLASS_NAMED("MrzReader")
@interface DOTDMrzReader : NSObject
/// Read MRZ in an image and return the result.
/// \param bgraRawImage Image to perform the MRZ reading on.
///
/// \param document Detection result for the document present in the image.
///
/// \param travelDocumentType Specify travel document type to improve MRZ reading accuracy. If travel document type is unknown, pass <code>nil</code>.
///
///
/// returns:
/// The result of MRZ reading.
- (DOTDMrzReaderResult * _Nonnull)readWithBgraRawImage:(DOTBgraRawImage * _Nonnull)bgraRawImage document:(DOTDDocumentDetectorDocument * _Nonnull)document travelDocumentType:(DOTTravelDocumentTypeWrapper * _Nullable)travelDocumentType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful.
SWIFT_CLASS_NAMED("ReadingError")
@interface DOTDMrzReaderReadingError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly) NSError * _Nullable internalError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// MRZ reading result.
SWIFT_CLASS_NAMED("Result")
@interface DOTDMrzReaderResult : NSObject
/// Lines of text recognized by OCR of the document.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rawLines;
/// Resolved travel document type.
@property (nonatomic, readonly, strong) DOTTravelDocumentTypeWrapper * _Nullable travelDocumentType;
/// Parsed MRZ.
@property (nonatomic, readonly, strong) DOTMachineReadableZone * _Nullable machineReadableZone;
/// Error thrown during MRZ reading.
@property (nonatomic, readonly, strong) DOTDMrzReaderReadingError * _Nullable error;
- (nonnull instancetype)initWithRawLines:(NSArray<NSString *> * _Nonnull)rawLines travelDocumentType:(DOTTravelDocumentTypeWrapper * _Nullable)travelDocumentType machineReadableZone:(DOTMachineReadableZone * _Nullable)machineReadableZone error:(DOTDMrzReaderReadingError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The result of using OCR on the MRZ text.
SWIFT_CLASS_NAMED("MrzRecognitionResult")
@interface DOTDMrzRecognitionResult : NSObject
/// Lines of text recognized by OCR of the document.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull rawLines;
/// Parsed MRZ.
@property (nonatomic, readonly, strong) DOTMachineReadableZone * _Nullable machineReadableZone;
- (nonnull instancetype)initWithRawLines:(NSArray<NSString *> * _Nonnull)rawLines machineReadableZone:(DOTMachineReadableZone * _Nullable)machineReadableZone OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Mode of MRZ (Machine Readable Zone) validation.
typedef SWIFT_ENUM_NAMED(NSInteger, DOTDMrzValidation, "MrzValidation", open) {
/// MRZ is not validated.
  DOTDMrzValidationNone = 0,
/// MRZ is validated only if it is present.
  DOTDMrzValidationValidateIfPresent = 1,
/// MRZ is always validated.
  DOTDMrzValidationValidateAlways = 2,
};

/// Represents the type of placeholder used in document auto-capture UI.
typedef SWIFT_ENUM_NAMED(NSInteger, DOTDPlaceholderType, "PlaceholderType", open) {
/// Placeholder with corners only.
  DOTDPlaceholderTypeCornersOnly = 0,
/// Placeholder with corners and MRZ (Machine Readable Zone) filler characters.
  DOTDPlaceholderTypeCornersAndMrzFillers = 1,
};


/// Validate minimum sharpness of the detected document.
/// To use this validator also following validators must be applied: <code>DocumentOutOfBoundsValidator</code>.
SWIFT_CLASS_NAMED("SharpnessTooLowValidator")
@interface DOTDSharpnessTooLowValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.65.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultThreshold;)
+ (double)defaultThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current minimal accepted sharpness.
@property (nonatomic, readonly) double threshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithThreshold:(double)threshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate sharpness of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for blurry document.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


/// Validate size of the detected document.
SWIFT_CLASS_NAMED("SizeTooSmallValidator")
@interface DOTDSizeTooSmallValidator : NSObject <DOTDDocumentAutoCaptureDetectionValidator>
/// Default threshold is 0.43.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultMinEdgeLengthToImageShorterSideRatioThreshold;)
+ (double)defaultMinEdgeLengthToImageShorterSideRatioThreshold SWIFT_WARN_UNUSED_RESULT;
/// Current minimal edge length to image shorter side ratio threshold.
@property (nonatomic, readonly) double minEdgeLengthToImageShorterSideRatioThreshold;
/// Validator identifier to address failed validation.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// Set of validator identifiers which represents a set of dependencies for this validator.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull dependencyIdentifiers;
/// Initialize with custom threshold.
- (nullable instancetype)initWithMinEdgeLengthToImageShorterSideRatioThreshold:(double)minEdgeLengthToImageShorterSideRatioThreshold error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initialize with default threshold.
- (nonnull instancetype)init;
/// Validate size of the detected document.
/// \param documentAutoCaptureFrameParameters Frame parameters to validate.
///
///
/// returns:
/// Returns <code>false</code> for small document.
- (BOOL)validateWithDocumentAutoCaptureFrameParameters:(DOTDDocumentAutoCaptureFrameParameters * _Nonnull)documentAutoCaptureFrameParameters SWIFT_WARN_UNUSED_RESULT;
@end


typedef SWIFT_ENUM_NAMED(NSInteger, DOTDValidationMode, "ValidationMode", open) {
/// Document must be clearly visible and sharp enough.
  DOTDValidationModeStandard = 0,
/// Document must be clearly visible, sharp enough and well aligned with the placeholder.
  DOTDValidationModeStrict = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
